// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blood_hospital_website.Data;

#nullable disable

namespace blood_hospital_website.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251231012402_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("blood_hospital_website.Models.Skor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OlumSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OyuncuAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sure")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skorlar");
                });
#pragma warning restore 612, 618
        }
    }
}
